websiteHost: "http://localhost:8080/"
maxFileSizeInKB: 1000
maxStorageSizePerUserInKB: 100000
fileStorageLocation: "C:\\Backed"
mysql:
  username: ""
  password: ""
  host: ""
  database: ""
  port: 3306
mailing:
  email: ""
  password: ""
  host: ""
  port: 465