#url to homepage of application
websiteHost: ""

#the maximum size of file that can be uploaded (in kilobytes)
# e.g. 1000 = 1MB
maxFileSizeInKB: 1000
#the maximum size of file that can be stored in memory (in kilobytes)
# e.g. 500 = 500KB
maxFileSizeInMemory: 500

#path to the folder of file storage
fileStorageLocation: ""

#mysql credentials
mysql:
  #username
  username: ""
  #password
  password: ""
  #host
  host: ""
  #database
  database: ""
  #port - default for mysql is 3306
  port: 3306

#mailing credentials
mailing:
  #email
  email: ""
  #password
  password: ""
  #host
  host: ""
  #port
  port: 0